all: false
dir: "{{.InterfaceDir}}"
filename: "{{.InterfaceFile | trimPrefix .InterfaceDir | trimPrefix \"/\" | trimSuffix \".go\"}}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
template: testify
packages:
  github.com/orbiqd/orbiqd-projectkit/pkg/agent:
    interfaces:
      Agent:
      Provider:
      Registry:
  github.com/orbiqd/orbiqd-projectkit/pkg/source:
    interfaces:
      Driver:
      DriverRepository:
      Resolver:
  github.com/orbiqd/orbiqd-projectkit/pkg/ai/instruction:
    interfaces:
      Repository:
  github.com/orbiqd/orbiqd-projectkit/pkg/ai/skill:
    interfaces:
      Repository:
  github.com/orbiqd/orbiqd-projectkit/pkg/ai/workflow:
    interfaces:
      Repository:
  github.com/orbiqd/orbiqd-projectkit/pkg/ai/mcp:
    interfaces:
      Repository:
  github.com/orbiqd/orbiqd-projectkit/pkg/project:
    interfaces:
      ConfigLoader:
  github.com/orbiqd/orbiqd-projectkit/pkg/doc/standard:
    interfaces:
      Renderer:
      Repository:
