agents:
  - kind: codex
    options:
      instructionsFileName: AGENTS_test.md
  - kind: claude
    options:
      instructionsFileName: AGENTS_claude.md
docs:
  standard:
    render:
      - destination: ./docs/standard
        format: markdown
rulebook:
  sources:
    - uri: local://./rulebooks/general
