agents:
  - kind: codex
    options:
      instructionsFileName: AGENTS_test.md
  - kind: claude
    options:
      instructionsFileName: AGENTS_claude.md
ai:
  instruction:
    sources:
      - uri: local://./rulebooks/general/ai/instructions
