// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package standard

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRenderer creates a new instance of MockRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenderer {
	mock := &MockRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRenderer is an autogenerated mock type for the Renderer type
type MockRenderer struct {
	mock.Mock
}

type MockRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenderer) EXPECT() *MockRenderer_Expecter {
	return &MockRenderer_Expecter{mock: &_m.Mock}
}

// FileExtension provides a mock function for the type MockRenderer
func (_mock *MockRenderer) FileExtension() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FileExtension")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRenderer_FileExtension_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExtension'
type MockRenderer_FileExtension_Call struct {
	*mock.Call
}

// FileExtension is a helper method to define mock.On call
func (_e *MockRenderer_Expecter) FileExtension() *MockRenderer_FileExtension_Call {
	return &MockRenderer_FileExtension_Call{Call: _e.mock.On("FileExtension")}
}

func (_c *MockRenderer_FileExtension_Call) Run(run func()) *MockRenderer_FileExtension_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenderer_FileExtension_Call) Return(s string) *MockRenderer_FileExtension_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRenderer_FileExtension_Call) RunAndReturn(run func() string) *MockRenderer_FileExtension_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function for the type MockRenderer
func (_mock *MockRenderer) Render(standard Standard) ([]byte, error) {
	ret := _mock.Called(standard)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Standard) ([]byte, error)); ok {
		return returnFunc(standard)
	}
	if returnFunc, ok := ret.Get(0).(func(Standard) []byte); ok {
		r0 = returnFunc(standard)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(Standard) error); ok {
		r1 = returnFunc(standard)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - standard Standard
func (_e *MockRenderer_Expecter) Render(standard interface{}) *MockRenderer_Render_Call {
	return &MockRenderer_Render_Call{Call: _e.mock.On("Render", standard)}
}

func (_c *MockRenderer_Render_Call) Run(run func(standard Standard)) *MockRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Standard
		if args[0] != nil {
			arg0 = args[0].(Standard)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenderer_Render_Call) Return(bytes []byte, err error) *MockRenderer_Render_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRenderer_Render_Call) RunAndReturn(run func(standard Standard) ([]byte, error)) *MockRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}
