// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package skill

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddSkill provides a mock function for the type MockRepository
func (_mock *MockRepository) AddSkill(skill Skill) error {
	ret := _mock.Called(skill)

	if len(ret) == 0 {
		panic("no return value specified for AddSkill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Skill) error); ok {
		r0 = returnFunc(skill)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddSkill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSkill'
type MockRepository_AddSkill_Call struct {
	*mock.Call
}

// AddSkill is a helper method to define mock.On call
//   - skill Skill
func (_e *MockRepository_Expecter) AddSkill(skill interface{}) *MockRepository_AddSkill_Call {
	return &MockRepository_AddSkill_Call{Call: _e.mock.On("AddSkill", skill)}
}

func (_c *MockRepository_AddSkill_Call) Run(run func(skill Skill)) *MockRepository_AddSkill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Skill
		if args[0] != nil {
			arg0 = args[0].(Skill)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_AddSkill_Call) Return(err error) *MockRepository_AddSkill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddSkill_Call) RunAndReturn(run func(skill Skill) error) *MockRepository_AddSkill_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll() ([]Skill, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Skill, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Skill); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetAll() *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockRepository_GetAll_Call) Run(run func()) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(skills []Skill, err error) *MockRepository_GetAll_Call {
	_c.Call.Return(skills, err)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func() ([]Skill, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkillByName provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSkillByName(name Name) (*Skill, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetSkillByName")
	}

	var r0 *Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Name) (*Skill, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(Name) *Skill); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(Name) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSkillByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkillByName'
type MockRepository_GetSkillByName_Call struct {
	*mock.Call
}

// GetSkillByName is a helper method to define mock.On call
//   - name Name
func (_e *MockRepository_Expecter) GetSkillByName(name interface{}) *MockRepository_GetSkillByName_Call {
	return &MockRepository_GetSkillByName_Call{Call: _e.mock.On("GetSkillByName", name)}
}

func (_c *MockRepository_GetSkillByName_Call) Run(run func(name Name)) *MockRepository_GetSkillByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Name
		if args[0] != nil {
			arg0 = args[0].(Name)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetSkillByName_Call) Return(skill *Skill, err error) *MockRepository_GetSkillByName_Call {
	_c.Call.Return(skill, err)
	return _c
}

func (_c *MockRepository_GetSkillByName_Call) RunAndReturn(run func(name Name) (*Skill, error)) *MockRepository_GetSkillByName_Call {
	_c.Call.Return(run)
	return _c
}
