// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package skill

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetByName provides a mock function for the type MockService
func (_mock *MockService) GetByName(ctx context.Context, name Name) (*Skill, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Name) (*Skill, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Name) *Skill); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Name) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockService_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name Name
func (_e *MockService_Expecter) GetByName(ctx interface{}, name interface{}) *MockService_GetByName_Call {
	return &MockService_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockService_GetByName_Call) Run(run func(ctx context.Context, name Name)) *MockService_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Name
		if args[1] != nil {
			arg1 = args[1].(Name)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByName_Call) Return(skill *Skill, err error) *MockService_GetByName_Call {
	_c.Call.Return(skill, err)
	return _c
}

func (_c *MockService_GetByName_Call) RunAndReturn(run func(ctx context.Context, name Name) (*Skill, error)) *MockService_GetByName_Call {
	_c.Call.Return(run)
	return _c
}
