// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workflow

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddExecution provides a mock function for the type MockRepository
func (_mock *MockRepository) AddExecution(execution Execution) error {
	ret := _mock.Called(execution)

	if len(ret) == 0 {
		panic("no return value specified for AddExecution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Execution) error); ok {
		r0 = returnFunc(execution)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddExecution'
type MockRepository_AddExecution_Call struct {
	*mock.Call
}

// AddExecution is a helper method to define mock.On call
//   - execution Execution
func (_e *MockRepository_Expecter) AddExecution(execution interface{}) *MockRepository_AddExecution_Call {
	return &MockRepository_AddExecution_Call{Call: _e.mock.On("AddExecution", execution)}
}

func (_c *MockRepository_AddExecution_Call) Run(run func(execution Execution)) *MockRepository_AddExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Execution
		if args[0] != nil {
			arg0 = args[0].(Execution)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_AddExecution_Call) Return(err error) *MockRepository_AddExecution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddExecution_Call) RunAndReturn(run func(execution Execution) error) *MockRepository_AddExecution_Call {
	_c.Call.Return(run)
	return _c
}

// AddWorkflow provides a mock function for the type MockRepository
func (_mock *MockRepository) AddWorkflow(workflow Workflow) error {
	ret := _mock.Called(workflow)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Workflow) error); ok {
		r0 = returnFunc(workflow)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkflow'
type MockRepository_AddWorkflow_Call struct {
	*mock.Call
}

// AddWorkflow is a helper method to define mock.On call
//   - workflow Workflow
func (_e *MockRepository_Expecter) AddWorkflow(workflow interface{}) *MockRepository_AddWorkflow_Call {
	return &MockRepository_AddWorkflow_Call{Call: _e.mock.On("AddWorkflow", workflow)}
}

func (_c *MockRepository_AddWorkflow_Call) Run(run func(workflow Workflow)) *MockRepository_AddWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Workflow
		if args[0] != nil {
			arg0 = args[0].(Workflow)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_AddWorkflow_Call) Return(err error) *MockRepository_AddWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddWorkflow_Call) RunAndReturn(run func(workflow Workflow) error) *MockRepository_AddWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWorkflows provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAllWorkflows() ([]Workflow, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllWorkflows")
	}

	var r0 []Workflow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Workflow, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Workflow); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Workflow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAllWorkflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWorkflows'
type MockRepository_GetAllWorkflows_Call struct {
	*mock.Call
}

// GetAllWorkflows is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetAllWorkflows() *MockRepository_GetAllWorkflows_Call {
	return &MockRepository_GetAllWorkflows_Call{Call: _e.mock.On("GetAllWorkflows")}
}

func (_c *MockRepository_GetAllWorkflows_Call) Run(run func()) *MockRepository_GetAllWorkflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetAllWorkflows_Call) Return(workflows []Workflow, err error) *MockRepository_GetAllWorkflows_Call {
	_c.Call.Return(workflows, err)
	return _c
}

func (_c *MockRepository_GetAllWorkflows_Call) RunAndReturn(run func() ([]Workflow, error)) *MockRepository_GetAllWorkflows_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionById provides a mock function for the type MockRepository
func (_mock *MockRepository) GetExecutionById(id ExecutionId) (*Execution, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionById")
	}

	var r0 *Execution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ExecutionId) (*Execution, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(ExecutionId) *Execution); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Execution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ExecutionId) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetExecutionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionById'
type MockRepository_GetExecutionById_Call struct {
	*mock.Call
}

// GetExecutionById is a helper method to define mock.On call
//   - id ExecutionId
func (_e *MockRepository_Expecter) GetExecutionById(id interface{}) *MockRepository_GetExecutionById_Call {
	return &MockRepository_GetExecutionById_Call{Call: _e.mock.On("GetExecutionById", id)}
}

func (_c *MockRepository_GetExecutionById_Call) Run(run func(id ExecutionId)) *MockRepository_GetExecutionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ExecutionId
		if args[0] != nil {
			arg0 = args[0].(ExecutionId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetExecutionById_Call) Return(execution *Execution, err error) *MockRepository_GetExecutionById_Call {
	_c.Call.Return(execution, err)
	return _c
}

func (_c *MockRepository_GetExecutionById_Call) RunAndReturn(run func(id ExecutionId) (*Execution, error)) *MockRepository_GetExecutionById_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowById provides a mock function for the type MockRepository
func (_mock *MockRepository) GetWorkflowById(id WorkflowId) (*Workflow, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowById")
	}

	var r0 *Workflow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(WorkflowId) (*Workflow, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(WorkflowId) *Workflow); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Workflow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(WorkflowId) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetWorkflowById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowById'
type MockRepository_GetWorkflowById_Call struct {
	*mock.Call
}

// GetWorkflowById is a helper method to define mock.On call
//   - id WorkflowId
func (_e *MockRepository_Expecter) GetWorkflowById(id interface{}) *MockRepository_GetWorkflowById_Call {
	return &MockRepository_GetWorkflowById_Call{Call: _e.mock.On("GetWorkflowById", id)}
}

func (_c *MockRepository_GetWorkflowById_Call) Run(run func(id WorkflowId)) *MockRepository_GetWorkflowById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 WorkflowId
		if args[0] != nil {
			arg0 = args[0].(WorkflowId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetWorkflowById_Call) Return(workflow *Workflow, err error) *MockRepository_GetWorkflowById_Call {
	_c.Call.Return(workflow, err)
	return _c
}

func (_c *MockRepository_GetWorkflowById_Call) RunAndReturn(run func(id WorkflowId) (*Workflow, error)) *MockRepository_GetWorkflowById_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllWorkflows provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveAllWorkflows() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllWorkflows")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveAllWorkflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllWorkflows'
type MockRepository_RemoveAllWorkflows_Call struct {
	*mock.Call
}

// RemoveAllWorkflows is a helper method to define mock.On call
func (_e *MockRepository_Expecter) RemoveAllWorkflows() *MockRepository_RemoveAllWorkflows_Call {
	return &MockRepository_RemoveAllWorkflows_Call{Call: _e.mock.On("RemoveAllWorkflows")}
}

func (_c *MockRepository_RemoveAllWorkflows_Call) Run(run func()) *MockRepository_RemoveAllWorkflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_RemoveAllWorkflows_Call) Return(err error) *MockRepository_RemoveAllWorkflows_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveAllWorkflows_Call) RunAndReturn(run func() error) *MockRepository_RemoveAllWorkflows_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExecution provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateExecution(execution Execution) error {
	ret := _mock.Called(execution)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExecution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Execution) error); ok {
		r0 = returnFunc(execution)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExecution'
type MockRepository_UpdateExecution_Call struct {
	*mock.Call
}

// UpdateExecution is a helper method to define mock.On call
//   - execution Execution
func (_e *MockRepository_Expecter) UpdateExecution(execution interface{}) *MockRepository_UpdateExecution_Call {
	return &MockRepository_UpdateExecution_Call{Call: _e.mock.On("UpdateExecution", execution)}
}

func (_c *MockRepository_UpdateExecution_Call) Run(run func(execution Execution)) *MockRepository_UpdateExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Execution
		if args[0] != nil {
			arg0 = args[0].(Execution)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateExecution_Call) Return(err error) *MockRepository_UpdateExecution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateExecution_Call) RunAndReturn(run func(execution Execution) error) *MockRepository_UpdateExecution_Call {
	_c.Call.Return(run)
	return _c
}
