// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package project

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigLoader creates a new instance of MockConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigLoader {
	mock := &MockConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigLoader is an autogenerated mock type for the ConfigLoader type
type MockConfigLoader struct {
	mock.Mock
}

type MockConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigLoader) EXPECT() *MockConfigLoader_Expecter {
	return &MockConfigLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockConfigLoader
func (_mock *MockConfigLoader) Load() (*Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfigLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockConfigLoader_Expecter) Load() *MockConfigLoader_Load_Call {
	return &MockConfigLoader_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockConfigLoader_Load_Call) Run(run func()) *MockConfigLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigLoader_Load_Call) Return(config *Config, err error) *MockConfigLoader_Load_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockConfigLoader_Load_Call) RunAndReturn(run func() (*Config, error)) *MockConfigLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
