// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package instruction

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddInstructions provides a mock function for the type MockRepository
func (_mock *MockRepository) AddInstructions(instructions Instructions) error {
	ret := _mock.Called(instructions)

	if len(ret) == 0 {
		panic("no return value specified for AddInstructions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Instructions) error); ok {
		r0 = returnFunc(instructions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddInstructions'
type MockRepository_AddInstructions_Call struct {
	*mock.Call
}

// AddInstructions is a helper method to define mock.On call
//   - instructions Instructions
func (_e *MockRepository_Expecter) AddInstructions(instructions interface{}) *MockRepository_AddInstructions_Call {
	return &MockRepository_AddInstructions_Call{Call: _e.mock.On("AddInstructions", instructions)}
}

func (_c *MockRepository_AddInstructions_Call) Run(run func(instructions Instructions)) *MockRepository_AddInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Instructions
		if args[0] != nil {
			arg0 = args[0].(Instructions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_AddInstructions_Call) Return(err error) *MockRepository_AddInstructions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddInstructions_Call) RunAndReturn(run func(instructions Instructions) error) *MockRepository_AddInstructions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll() ([]Instructions, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []Instructions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Instructions, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Instructions); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Instructions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetAll() *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockRepository_GetAll_Call) Run(run func()) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(instructionss []Instructions, err error) *MockRepository_GetAll_Call {
	_c.Call.Return(instructionss, err)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func() ([]Instructions, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockRepository_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
func (_e *MockRepository_Expecter) RemoveAll() *MockRepository_RemoveAll_Call {
	return &MockRepository_RemoveAll_Call{Call: _e.mock.On("RemoveAll")}
}

func (_c *MockRepository_RemoveAll_Call) Run(run func()) *MockRepository_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_RemoveAll_Call) Return(err error) *MockRepository_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveAll_Call) RunAndReturn(run func() error) *MockRepository_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}
