// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package source

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriverRepository creates a new instance of MockDriverRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriverRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriverRepository {
	mock := &MockDriverRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriverRepository is an autogenerated mock type for the DriverRepository type
type MockDriverRepository struct {
	mock.Mock
}

type MockDriverRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriverRepository) EXPECT() *MockDriverRepository_Expecter {
	return &MockDriverRepository_Expecter{mock: &_m.Mock}
}

// GetDriverByScheme provides a mock function for the type MockDriverRepository
func (_mock *MockDriverRepository) GetDriverByScheme(scheme string) (Driver, error) {
	ret := _mock.Called(scheme)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverByScheme")
	}

	var r0 Driver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Driver, error)); ok {
		return returnFunc(scheme)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Driver); ok {
		r0 = returnFunc(scheme)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Driver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(scheme)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriverRepository_GetDriverByScheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverByScheme'
type MockDriverRepository_GetDriverByScheme_Call struct {
	*mock.Call
}

// GetDriverByScheme is a helper method to define mock.On call
//   - scheme string
func (_e *MockDriverRepository_Expecter) GetDriverByScheme(scheme interface{}) *MockDriverRepository_GetDriverByScheme_Call {
	return &MockDriverRepository_GetDriverByScheme_Call{Call: _e.mock.On("GetDriverByScheme", scheme)}
}

func (_c *MockDriverRepository_GetDriverByScheme_Call) Run(run func(scheme string)) *MockDriverRepository_GetDriverByScheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriverRepository_GetDriverByScheme_Call) Return(driver Driver, err error) *MockDriverRepository_GetDriverByScheme_Call {
	_c.Call.Return(driver, err)
	return _c
}

func (_c *MockDriverRepository_GetDriverByScheme_Call) RunAndReturn(run func(scheme string) (Driver, error)) *MockDriverRepository_GetDriverByScheme_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDriver provides a mock function for the type MockDriverRepository
func (_mock *MockDriverRepository) RegisterDriver(driver Driver) error {
	ret := _mock.Called(driver)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDriver")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Driver) error); ok {
		r0 = returnFunc(driver)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriverRepository_RegisterDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDriver'
type MockDriverRepository_RegisterDriver_Call struct {
	*mock.Call
}

// RegisterDriver is a helper method to define mock.On call
//   - driver Driver
func (_e *MockDriverRepository_Expecter) RegisterDriver(driver interface{}) *MockDriverRepository_RegisterDriver_Call {
	return &MockDriverRepository_RegisterDriver_Call{Call: _e.mock.On("RegisterDriver", driver)}
}

func (_c *MockDriverRepository_RegisterDriver_Call) Run(run func(driver Driver)) *MockDriverRepository_RegisterDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Driver
		if args[0] != nil {
			arg0 = args[0].(Driver)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriverRepository_RegisterDriver_Call) Return(err error) *MockDriverRepository_RegisterDriver_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriverRepository_RegisterDriver_Call) RunAndReturn(run func(driver Driver) error) *MockDriverRepository_RegisterDriver_Call {
	_c.Call.Return(run)
	return _c
}
