// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package source

import (
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// GetSupportedSchemes provides a mock function for the type MockDriver
func (_mock *MockDriver) GetSupportedSchemes() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSupportedSchemes")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockDriver_GetSupportedSchemes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupportedSchemes'
type MockDriver_GetSupportedSchemes_Call struct {
	*mock.Call
}

// GetSupportedSchemes is a helper method to define mock.On call
func (_e *MockDriver_Expecter) GetSupportedSchemes() *MockDriver_GetSupportedSchemes_Call {
	return &MockDriver_GetSupportedSchemes_Call{Call: _e.mock.On("GetSupportedSchemes")}
}

func (_c *MockDriver_GetSupportedSchemes_Call) Run(run func()) *MockDriver_GetSupportedSchemes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_GetSupportedSchemes_Call) Return(strings []string) *MockDriver_GetSupportedSchemes_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockDriver_GetSupportedSchemes_Call) RunAndReturn(run func() []string) *MockDriver_GetSupportedSchemes_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockDriver
func (_mock *MockDriver) Resolve(uri string) (afero.Fs, error) {
	ret := _mock.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 afero.Fs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.Fs, error)); ok {
		return returnFunc(uri)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.Fs); ok {
		r0 = returnFunc(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.Fs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockDriver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - uri string
func (_e *MockDriver_Expecter) Resolve(uri interface{}) *MockDriver_Resolve_Call {
	return &MockDriver_Resolve_Call{Call: _e.mock.On("Resolve", uri)}
}

func (_c *MockDriver_Resolve_Call) Run(run func(uri string)) *MockDriver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDriver_Resolve_Call) Return(fs afero.Fs, err error) *MockDriver_Resolve_Call {
	_c.Call.Return(fs, err)
	return _c
}

func (_c *MockDriver_Resolve_Call) RunAndReturn(run func(uri string) (afero.Fs, error)) *MockDriver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
