// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package source

import (
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockResolver
func (_mock *MockResolver) Resolve(uri string) (afero.Fs, error) {
	ret := _mock.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 afero.Fs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.Fs, error)); ok {
		return returnFunc(uri)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.Fs); ok {
		r0 = returnFunc(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.Fs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - uri string
func (_e *MockResolver_Expecter) Resolve(uri interface{}) *MockResolver_Resolve_Call {
	return &MockResolver_Resolve_Call{Call: _e.mock.On("Resolve", uri)}
}

func (_c *MockResolver_Resolve_Call) Run(run func(uri string)) *MockResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResolver_Resolve_Call) Return(fs afero.Fs, err error) *MockResolver_Resolve_Call {
	_c.Call.Return(fs, err)
	return _c
}

func (_c *MockResolver_Resolve_Call) RunAndReturn(run func(uri string) (afero.Fs, error)) *MockResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
