// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agent

import (
	"github.com/orbiqd/orbiqd-projectkit/pkg/ai/instruction"
	"github.com/orbiqd/orbiqd-projectkit/pkg/ai/mcp"
	"github.com/orbiqd/orbiqd-projectkit/pkg/ai/skill"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgent creates a new instance of MockAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgent {
	mock := &MockAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgent is an autogenerated mock type for the Agent type
type MockAgent struct {
	mock.Mock
}

type MockAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgent) EXPECT() *MockAgent_Expecter {
	return &MockAgent_Expecter{mock: &_m.Mock}
}

// GetKind provides a mock function for the type MockAgent
func (_mock *MockAgent) GetKind() Kind {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKind")
	}

	var r0 Kind
	if returnFunc, ok := ret.Get(0).(func() Kind); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Kind)
	}
	return r0
}

// MockAgent_GetKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKind'
type MockAgent_GetKind_Call struct {
	*mock.Call
}

// GetKind is a helper method to define mock.On call
func (_e *MockAgent_Expecter) GetKind() *MockAgent_GetKind_Call {
	return &MockAgent_GetKind_Call{Call: _e.mock.On("GetKind")}
}

func (_c *MockAgent_GetKind_Call) Run(run func()) *MockAgent_GetKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_GetKind_Call) Return(kind Kind) *MockAgent_GetKind_Call {
	_c.Call.Return(kind)
	return _c
}

func (_c *MockAgent_GetKind_Call) RunAndReturn(run func() Kind) *MockAgent_GetKind_Call {
	_c.Call.Return(run)
	return _c
}

// GitIgnorePatterns provides a mock function for the type MockAgent
func (_mock *MockAgent) GitIgnorePatterns() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GitIgnorePatterns")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockAgent_GitIgnorePatterns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GitIgnorePatterns'
type MockAgent_GitIgnorePatterns_Call struct {
	*mock.Call
}

// GitIgnorePatterns is a helper method to define mock.On call
func (_e *MockAgent_Expecter) GitIgnorePatterns() *MockAgent_GitIgnorePatterns_Call {
	return &MockAgent_GitIgnorePatterns_Call{Call: _e.mock.On("GitIgnorePatterns")}
}

func (_c *MockAgent_GitIgnorePatterns_Call) Run(run func()) *MockAgent_GitIgnorePatterns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_GitIgnorePatterns_Call) Return(strings []string) *MockAgent_GitIgnorePatterns_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockAgent_GitIgnorePatterns_Call) RunAndReturn(run func() []string) *MockAgent_GitIgnorePatterns_Call {
	_c.Call.Return(run)
	return _c
}

// RebuildSkills provides a mock function for the type MockAgent
func (_mock *MockAgent) RebuildSkills(skillRepository skill.Repository) error {
	ret := _mock.Called(skillRepository)

	if len(ret) == 0 {
		panic("no return value specified for RebuildSkills")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(skill.Repository) error); ok {
		r0 = returnFunc(skillRepository)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_RebuildSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebuildSkills'
type MockAgent_RebuildSkills_Call struct {
	*mock.Call
}

// RebuildSkills is a helper method to define mock.On call
//   - skillRepository skill.Repository
func (_e *MockAgent_Expecter) RebuildSkills(skillRepository interface{}) *MockAgent_RebuildSkills_Call {
	return &MockAgent_RebuildSkills_Call{Call: _e.mock.On("RebuildSkills", skillRepository)}
}

func (_c *MockAgent_RebuildSkills_Call) Run(run func(skillRepository skill.Repository)) *MockAgent_RebuildSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 skill.Repository
		if args[0] != nil {
			arg0 = args[0].(skill.Repository)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_RebuildSkills_Call) Return(err error) *MockAgent_RebuildSkills_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_RebuildSkills_Call) RunAndReturn(run func(skillRepository skill.Repository) error) *MockAgent_RebuildSkills_Call {
	_c.Call.Return(run)
	return _c
}

// RenderInstructions provides a mock function for the type MockAgent
func (_mock *MockAgent) RenderInstructions(instructions []instruction.Instructions) error {
	ret := _mock.Called(instructions)

	if len(ret) == 0 {
		panic("no return value specified for RenderInstructions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]instruction.Instructions) error); ok {
		r0 = returnFunc(instructions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_RenderInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderInstructions'
type MockAgent_RenderInstructions_Call struct {
	*mock.Call
}

// RenderInstructions is a helper method to define mock.On call
//   - instructions []instruction.Instructions
func (_e *MockAgent_Expecter) RenderInstructions(instructions interface{}) *MockAgent_RenderInstructions_Call {
	return &MockAgent_RenderInstructions_Call{Call: _e.mock.On("RenderInstructions", instructions)}
}

func (_c *MockAgent_RenderInstructions_Call) Run(run func(instructions []instruction.Instructions)) *MockAgent_RenderInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []instruction.Instructions
		if args[0] != nil {
			arg0 = args[0].([]instruction.Instructions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_RenderInstructions_Call) Return(err error) *MockAgent_RenderInstructions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_RenderInstructions_Call) RunAndReturn(run func(instructions []instruction.Instructions) error) *MockAgent_RenderInstructions_Call {
	_c.Call.Return(run)
	return _c
}

// RenderMCPServers provides a mock function for the type MockAgent
func (_mock *MockAgent) RenderMCPServers(mcpServer mcp.MCPServer) error {
	ret := _mock.Called(mcpServer)

	if len(ret) == 0 {
		panic("no return value specified for RenderMCPServers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(mcp.MCPServer) error); ok {
		r0 = returnFunc(mcpServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_RenderMCPServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderMCPServers'
type MockAgent_RenderMCPServers_Call struct {
	*mock.Call
}

// RenderMCPServers is a helper method to define mock.On call
//   - mcpServer mcp.MCPServer
func (_e *MockAgent_Expecter) RenderMCPServers(mcpServer interface{}) *MockAgent_RenderMCPServers_Call {
	return &MockAgent_RenderMCPServers_Call{Call: _e.mock.On("RenderMCPServers", mcpServer)}
}

func (_c *MockAgent_RenderMCPServers_Call) Run(run func(mcpServer mcp.MCPServer)) *MockAgent_RenderMCPServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 mcp.MCPServer
		if args[0] != nil {
			arg0 = args[0].(mcp.MCPServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_RenderMCPServers_Call) Return(err error) *MockAgent_RenderMCPServers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_RenderMCPServers_Call) RunAndReturn(run func(mcpServer mcp.MCPServer) error) *MockAgent_RenderMCPServers_Call {
	_c.Call.Return(run)
	return _c
}
