// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agent

import (
	"github.com/orbiqd/orbiqd-projectkit/pkg/ai/instruction"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgent creates a new instance of MockAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgent {
	mock := &MockAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgent is an autogenerated mock type for the Agent type
type MockAgent struct {
	mock.Mock
}

type MockAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgent) EXPECT() *MockAgent_Expecter {
	return &MockAgent_Expecter{mock: &_m.Mock}
}

// RenderInstructions provides a mock function for the type MockAgent
func (_mock *MockAgent) RenderInstructions(instructions []instruction.Instructions) error {
	ret := _mock.Called(instructions)

	if len(ret) == 0 {
		panic("no return value specified for RenderInstructions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]instruction.Instructions) error); ok {
		r0 = returnFunc(instructions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_RenderInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderInstructions'
type MockAgent_RenderInstructions_Call struct {
	*mock.Call
}

// RenderInstructions is a helper method to define mock.On call
//   - instructions []instruction.Instructions
func (_e *MockAgent_Expecter) RenderInstructions(instructions interface{}) *MockAgent_RenderInstructions_Call {
	return &MockAgent_RenderInstructions_Call{Call: _e.mock.On("RenderInstructions", instructions)}
}

func (_c *MockAgent_RenderInstructions_Call) Run(run func(instructions []instruction.Instructions)) *MockAgent_RenderInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []instruction.Instructions
		if args[0] != nil {
			arg0 = args[0].([]instruction.Instructions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_RenderInstructions_Call) Return(err error) *MockAgent_RenderInstructions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_RenderInstructions_Call) RunAndReturn(run func(instructions []instruction.Instructions) error) *MockAgent_RenderInstructions_Call {
	_c.Call.Return(run)
	return _c
}
