// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agent

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// GetKind provides a mock function for the type MockProvider
func (_mock *MockProvider) GetKind() Kind {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKind")
	}

	var r0 Kind
	if returnFunc, ok := ret.Get(0).(func() Kind); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Kind)
	}
	return r0
}

// MockProvider_GetKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKind'
type MockProvider_GetKind_Call struct {
	*mock.Call
}

// GetKind is a helper method to define mock.On call
func (_e *MockProvider_Expecter) GetKind() *MockProvider_GetKind_Call {
	return &MockProvider_GetKind_Call{Call: _e.mock.On("GetKind")}
}

func (_c *MockProvider_GetKind_Call) Run(run func()) *MockProvider_GetKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_GetKind_Call) Return(kind Kind) *MockProvider_GetKind_Call {
	_c.Call.Return(kind)
	return _c
}

func (_c *MockProvider_GetKind_Call) RunAndReturn(run func() Kind) *MockProvider_GetKind_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgent provides a mock function for the type MockProvider
func (_mock *MockProvider) NewAgent(options any) (Agent, error) {
	ret := _mock.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for NewAgent")
	}

	var r0 Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) (Agent, error)); ok {
		return returnFunc(options)
	}
	if returnFunc, ok := ret.Get(0).(func(any) Agent); ok {
		r0 = returnFunc(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_NewAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAgent'
type MockProvider_NewAgent_Call struct {
	*mock.Call
}

// NewAgent is a helper method to define mock.On call
//   - options any
func (_e *MockProvider_Expecter) NewAgent(options interface{}) *MockProvider_NewAgent_Call {
	return &MockProvider_NewAgent_Call{Call: _e.mock.On("NewAgent", options)}
}

func (_c *MockProvider_NewAgent_Call) Run(run func(options any)) *MockProvider_NewAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_NewAgent_Call) Return(agent Agent, err error) *MockProvider_NewAgent_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *MockProvider_NewAgent_Call) RunAndReturn(run func(options any) (Agent, error)) *MockProvider_NewAgent_Call {
	_c.Call.Return(run)
	return _c
}
