// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agent

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// GetAllKinds provides a mock function for the type MockRegistry
func (_mock *MockRegistry) GetAllKinds() []Kind {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllKinds")
	}

	var r0 []Kind
	if returnFunc, ok := ret.Get(0).(func() []Kind); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Kind)
		}
	}
	return r0
}

// MockRegistry_GetAllKinds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllKinds'
type MockRegistry_GetAllKinds_Call struct {
	*mock.Call
}

// GetAllKinds is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) GetAllKinds() *MockRegistry_GetAllKinds_Call {
	return &MockRegistry_GetAllKinds_Call{Call: _e.mock.On("GetAllKinds")}
}

func (_c *MockRegistry_GetAllKinds_Call) Run(run func()) *MockRegistry_GetAllKinds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_GetAllKinds_Call) Return(kinds []Kind) *MockRegistry_GetAllKinds_Call {
	_c.Call.Return(kinds)
	return _c
}

func (_c *MockRegistry_GetAllKinds_Call) RunAndReturn(run func() []Kind) *MockRegistry_GetAllKinds_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKind provides a mock function for the type MockRegistry
func (_mock *MockRegistry) GetByKind(kind Kind) (Provider, error) {
	ret := _mock.Called(kind)

	if len(ret) == 0 {
		panic("no return value specified for GetByKind")
	}

	var r0 Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Kind) (Provider, error)); ok {
		return returnFunc(kind)
	}
	if returnFunc, ok := ret.Get(0).(func(Kind) Provider); ok {
		r0 = returnFunc(kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Provider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(Kind) error); ok {
		r1 = returnFunc(kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_GetByKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKind'
type MockRegistry_GetByKind_Call struct {
	*mock.Call
}

// GetByKind is a helper method to define mock.On call
//   - kind Kind
func (_e *MockRegistry_Expecter) GetByKind(kind interface{}) *MockRegistry_GetByKind_Call {
	return &MockRegistry_GetByKind_Call{Call: _e.mock.On("GetByKind", kind)}
}

func (_c *MockRegistry_GetByKind_Call) Run(run func(kind Kind)) *MockRegistry_GetByKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Kind
		if args[0] != nil {
			arg0 = args[0].(Kind)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_GetByKind_Call) Return(provider Provider, err error) *MockRegistry_GetByKind_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockRegistry_GetByKind_Call) RunAndReturn(run func(kind Kind) (Provider, error)) *MockRegistry_GetByKind_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Register(provider Provider) error {
	ret := _mock.Called(provider)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Provider) error); ok {
		r0 = returnFunc(provider)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - provider Provider
func (_e *MockRegistry_Expecter) Register(provider interface{}) *MockRegistry_Register_Call {
	return &MockRegistry_Register_Call{Call: _e.mock.On("Register", provider)}
}

func (_c *MockRegistry_Register_Call) Run(run func(provider Provider)) *MockRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Provider
		if args[0] != nil {
			arg0 = args[0].(Provider)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Register_Call) Return(err error) *MockRegistry_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_Register_Call) RunAndReturn(run func(provider Provider) error) *MockRegistry_Register_Call {
	_c.Call.Return(run)
	return _c
}
